------------------------------------------------------------------------------------------------------------------------

[2020-04-03 00:14:27 #1 store] 
Database 'C:\Users\Usuario\git\Sprint_2\Sprint_2\resources\bets.temp' is opened by 15016@DESKTOP-00OS7EM

[2020-04-03 00:14:27 #2 store] 
Configuration path: C:\Users\Usuario\git\Sprint_2\objectdb-2.8.2\objectdb.conf

[2020-04-03 00:14:33 #3 store] 
Database 'C:\Users\Usuario\git\Sprint_2\Sprint_2\resources\bets.temp' is closed by 15016@DESKTOP-00OS7EM

------------------------------------------------------------------------------------------------------------------------

[2020-04-03 16:45:36 #1 store] 
Database 'C:\Users\Usuario\git\Sprint_2\Sprint_2\resources\bets.temp' is opened by 13072@DESKTOP-00OS7EM

[2020-04-03 16:45:36 #2 store] 
Configuration path: C:\Users\Usuario\git\Sprint_2\objectdb-2.8.2\objectdb.conf

[2020-04-03 16:46:29 #3 store] 
Database 'C:\Users\Usuario\git\Sprint_2\Sprint_2\resources\bets.temp' is closed by 13072@DESKTOP-00OS7EM

------------------------------------------------------------------------------------------------------------------------

[2020-04-03 18:22:14 #1 store] 
Database 'C:\Users\Usuario\git\Sprint_2\Sprint_2\resources\bets.temp' is opened by 18112@DESKTOP-00OS7EM

[2020-04-03 18:22:14 #2 store] 
Configuration path: C:\Users\Usuario\git\Sprint_2\objectdb-2.8.2\objectdb.conf

[2020-04-03 18:22:24 #3 store] 
Database 'C:\Users\Usuario\git\Sprint_2\Sprint_2\resources\bets.temp' is closed by 18112@DESKTOP-00OS7EM

------------------------------------------------------------------------------------------------------------------------

[2020-04-03 18:22:35 #1 explorer] 
[ObjectDB 2.8.2] javax.persistence.PersistenceException
Attempt to open a database file 'C:\Users\Usuario\git\Sprint_2\Sprint_2\resources\bets.temp' that is currently in use by another process (error 141)
	at com.objectdb.Explorer$1.run(Explorer.java:57)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.objectdb.o.UserException: Attempt to open a database file 'C:\Users\Usuario\git\Sprint_2\Sprint_2\resources\bets.temp' that is currently in use by another process
	at com.objectdb.o.MSG.a(MSG.java:64)
	at com.objectdb.o.LFL.J(LFL.java:930)
	at com.objectdb.o.LFL.x(LFL.java:887)
	at com.objectdb.o.LFL.x(LFL.java:797)
	at com.objectdb.o.DFL.<init>(DFL.java:241)
	at com.objectdb.o.DMG.<init>(DMG.java:27)
	at com.objectdb.o.MST.<init>(MST.java:127)
	at com.objectdb.o.MST.ap(MST.java:109)
	at com.objectdb.o.MSF.Y3(MSF.java:190)
	at com.objectdb.o.OMF.s(OMF.java:804)
	at com.objectdb.jpa.EMF.s(EMF.java:130)
	at com.objectdb.o.OMF.x(OMF.java:715)
	at com.objectdb.jpa.EMF.createEntityManager(EMF.java:149)
	... 17 more

